#!/bin/bash
# Script to help find Raydium pool addresses
# Visit these URLs in your browser to find the correct pool addresses:

echo "=== Finding Raydium Pool Addresses ==="
echo ""
echo "Visit these websites to find the correct pool addresses:"
echo ""
echo "1. Birdeye - Best for finding pool addresses"
echo "   https://birdeye.so/token/[TOKEN_MINT_ADDRESS]?chain=solana"
echo ""
echo "2. Solscan - Blockchain explorer"
echo "   https://solscan.io/"
echo ""
echo "3. Raydium Official - Direct from source"
echo "   https://raydium.io/swap/"
echo ""
echo "=== Token Mint Addresses to Search ==="
echo "BONK: DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263"
echo "WIF: EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzLHYxdM65zcjm"
echo "POPCAT: 7GCihgDB8fe6KNjn2MYtkzZcRjQy3t9GHdC8uHYmW2hr"
echo ""
echo "=== How to Find Pool Address ==="
echo "1. Go to Birdeye.so"
echo "2. Search for the token (e.g., 'BONK')"
echo "3. Click on the token"
echo "4. Look for 'Liquidity Pools' section"
echo "5. Find the Raydium pool with USDC pair"
echo "6. Copy the pool address"
echo ""
echo "=== Alternative: Use Raydium API ==="
echo "curl 'https://api.raydium.io/v2/main/pairs' | jq '.[] | select(.name | contains(\"BONK\"))'"
echo ""

